BOT_TOKEN = "5690182610:AAEWA4QYEbpgoMN5gKX578Fa8G_DUNTLchU"

API_KEY = "8sM62WsjOVn7JIvkiPRM6Z4FNoTdrbFL"
API_URL = 'https://api.apilayer.com/fixer'
WIKI_URL = "https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%B7%D0%BD%D0%B0%D0%BA%D0%BE%D0%B2_%D0%B2%D0%B0%D0%BB%D1%8E%D1%82"
POPULAR_CURRENCIES = {
    "доллар": "USD",
    "евро": "EUR",
    "рубль": "RUB",
    "бел. рубль": "BYN",
    "юань": "CNY",
    "фунт": "GBP",
}
WIKI_CURRENCIES = {
    'AED': 'Дирхам(Объединённые Арабские Эмираты)',
    'AFN': 'Афгани(Афганистан)',
    'ALL': 'Лек(Албания)',
    'AMD': 'Драм(Армения)',
    'ANG': 'Гульден(Нидерландские Антильские острова)',
    'AOA': 'Кванза(Ангола)',
    'ARS': 'Песо(Аргентина)',
    'AUD': 'Доллар(Австралия)',
    'AWG': 'Флорин(Аруба)',
    'AZN': 'Манат(Азербайджан)',
    'BAM': 'Марка конвертируемая(Босния и Герцеговина)',
    'BBD': 'Доллар(Барбадос)',
    'BDT': 'Така(Бангладеш)',
    'BGN': 'Лев(Болгария)',
    'BHD': 'Динар(Бахрейн)',
    'BIF': 'Франк(Бурунди)',
    'BMD': 'Доллар(Бермудские острова)',
    'BND': 'Доллар(Бруней)',
    'BOB': 'Боливиано(Боливия)',
    'BRL': 'Реал(Бразилия)',
    'BSD': 'Доллар(Багамы)',
    'BTN': 'Нгултрум(Бутан)',
    'BWP': 'Пула(Ботсвана)',
    'BYN': 'Рубль(Белоруссия)',
    'BZD': 'Доллар(Белиз)',
    'CAD': 'Доллар(Канада)',
    'CDF': 'Франк(Демократическая Республика Конго)',
    'CHF': 'Франк(Швейцария)',
    'CLP': 'Песо(Чили)',
    'CNY': 'Юань(Китай)',
    'COP': 'Песо(Колумбия)',
    'CRC': 'Колон(Коста-Рика)',
    'CUP': 'Песо(Куба)',
    'CVE': 'Эскудо(Кабо-Верде)',
    'CZK': 'Крона(Чехия)',
    'DJF': 'Франк(Джибути)',
    'DKK': 'Крона(Дания)',
    'DOP': 'Песо(Доминиканская республика)',
    'DZD': 'Динар(Алжир)',
    'EGP': 'Фунт(Египет)',
    'ERN': 'Накфа(Эритрея)',
    'ETB': 'Быр(Эфиопия)',
    'EUR': 'Евро(Страны Еврозоны)',
    'FJD': 'Доллар(Фиджи)',
    'FKP': 'Фунт(Фолклендские острова)',
    'GBP': 'Фунт стерлингов(Великобритания)',
    'GEL': 'Лари(Грузия)',
    'GHS': 'Седи(Гана)',
    'GIP': 'Фунт(Гибралтар)',
    'GMD': 'Даласи(Гамбия)',
    'GNF': 'Франк(Гвинея)',
    'GTQ': 'Кетсаль(Гватемала)',
    'GYD': 'Доллар(Гайана)',
    'HKD': 'Доллар(Гонконг)',
    'HNL': 'Лемпира(Гондурас)',
    'HRK': 'Куна(Хорватия)',
    'HTG': 'Гурд(Гаити)',
    'HUF': 'Форинт(Венгрия)',
    'IDR': 'Рупия(Индонезия)',
    'ILS': 'Шекель новый(Израиль)',
    'INR': 'Рупия(Индия)',
    'IQD': 'Динар(Ирак)',
    'IRR': 'Риал(Иран)',
    'ISK': 'Крона(Исландия)',
    'JMD': 'Доллар(Ямайка)',
    'JOD': 'Динар(Иордания)',
    'JPY': 'Иена(Япония)',
    'KES': 'Шиллинг(Кения)',
    'KGS': 'Сом(Киргизия)',
    'KHR': 'Риель(Камбоджа)',
    'KMF': 'Франк(Коморы)',
    'KPW': 'Вона(Северная Корея)',
    'KRW': 'Вона(Южная Корея)',
    'KWD': 'Динар(Кувейт)',
    'KYD': 'Доллар(Каймановы острова)',
    'KZT': 'Тенге(Казахстан)',
    'LAK': 'Кип(Лаос)',
    'LBP': 'Фунт(Ливан)',
    'LKR': 'Рупия(Шри-Ланка)',
    'LRD': 'Доллар(Либерия)',
    'LSL': 'Лоти(Лесото)',
    'LTL': 'Лит(Литва)',
    'LVL': 'Лат(Латвия)',
    'LYD': 'Динар(Ливия)',
    'MAD': 'Дирхам(Марокко)',
    'MDL': 'Лей(Молдавия)',
    'MGA': 'Ариари(Мадагаскар)',
    'MKD': 'Денар(Северная Македония)',
    'MMK': 'Кьят(Мьянма)',
    'MNT': 'Тугрик(Монголия)',
    'MOP': 'Патака(Макао)',
    'MRO': 'Угия(Мавритания)',
    'MUR': 'Рупия(Маврикий)',
    'MVR': 'Руфия(Мальдивы)',
    'MWK': 'Квача(Малави)',
    'MXN': 'Песо(Мексика)',
    'MYR': 'Ринггит(Малайзия)',
    'MZN': 'Метикал(Мозамбик)',
    'NAD': 'Доллар(Намибия)',
    'NGN': 'Найра(Нигерия)',
    'NIO': 'Кордоба(Никарагуа)',
    'NOK': 'Крона(Норвегия)',
    'NPR': 'Рупия(Непал)',
    'NZD': 'Доллар(Новая Зеландия)',
    'OMR': 'Риал(Оман)',
    'PAB': 'Бальбоа(Панама)',
    'PEN': 'Соль новый(Перу)',
    'PGK': 'Кина(Папуа — Новая Гвинея)',
    'PHP': 'Песо(Филиппины)',
    'PKR': 'Рупия(Пакистан)',
    'PLN': 'Злотый(Польша)',
    'PYG': 'Гуарани(Парагвай)',
    'QAR': 'Риал(Катар)',
    'RON': 'Лей новый(Румыния)',
    'RSD': 'Динар(Сербия)',
    'RUB': 'Рубль(Россия)',
    'RWF': 'Франк(Руанда)',
    'SAR': 'Риял(Саудовская Аравия)',
    'SBD': 'Доллар(Соломоновы Острова)',
    'SCR': 'Рупия(Сейшелы)',
    'SDG': 'Фунт(Судан)',
    'SEK': 'Крона(Швеция)',
    'SGD': 'Доллар(Сингапур)',
    'SHP': 'Фунт(Остров Святой Елены)',
    'SLL': 'Леоне(Сьерра-Леоне)',
    'SOS': 'Шиллинг(Сомали)',
    'SRD': 'Доллар(Суринам)',
    'STN': 'Добра(Сан-Томе и Принсипи)',
    'SYP': 'Фунт(Сирия)',
    'SZL': 'Лилангени(Свазиленд)',
    'THB': 'Бат(Таиланд)',
    'TJS': 'Сомони(Таджикистан)',
    'TMТ': 'Манат(Туркмения)',
    'TND': 'Динар(Тунис)',
    'TOP': 'Паанга(Тонга)',
    'TRY': 'Лира(Турция)',
    'TTD': 'Доллар(Тринидад и Тобаго)',
    'TWD': 'Доллар новый(Тайвань)',
    'TZS': 'Шиллинг(Танзания)',
    'UAH': 'Гривна(Украина)',
    'UGX': 'Шиллинг(Уганда)',
    'USD': 'Доллар(США)',
    'UYU': 'Песо(Уругвай)',
    'UZS': 'Сум(Узбекистан)',
    'VEF': 'Боливар фуэрте(Венесуэла)',
    'VND': 'Донг(Вьетнам)',
    'VUV': 'Вату(Вануату)',
    'WST': 'Тала(Самоа)',
    'XAF': 'Франк КФА(BEAC)[62](Страны ЦАВЭС (CEMAC): Габон •  Камерун Республика '
           'Конго ЦАР •  Чад Экваториальная Гвинея)',
    'XCD': 'Доллар(Страны ОВКГ (OECS): Ангилья •  Антигуа и Барбуда Гренада •  '
           'Доминика Монтсеррат •  Сент-Люсия Сент-Винсент и Гренадины Сент-Китс '
           'и Невис)',
    'XOF': 'Франк КФА(BCEAO)[61](Страны ЗАЭВС (UEMOA): Бенин •  Буркина-Фасо '
           'Кот-д’Ивуар Гвинея-Бисау Мали •  Нигер Сенегал •  Того)',
    'XPF': 'Франк КПФ(Заморские владения Франции: Французская Полинезия Новая '
           'Каледония Уоллис и Футуна)',
    'YER': 'Риал(Йемен)',
    'ZAR': 'Рэнд(ЮАР)',
    'ZMK': 'Квача(Замбия)',
    'ZWD': 'Доллар(Зимбабве)',
}

CURRENCIES = {'AED': 'United Arab Emirates Dirham',
              'AFN': 'Afghan Afghani',
              'ALL': 'Albanian Lek',
              'AMD': 'Armenian Dram',
              'ANG': 'Netherlands Antillean Guilder',
              'AOA': 'Angolan Kwanza',
              'ARS': 'Argentine Peso',
              'AUD': 'Australian Dollar',
              'AWG': 'Aruban Florin',
              'AZN': 'Azerbaijani Manat',
              'BAM': 'Bosnia-Herzegovina Convertible Mark',
              'BBD': 'Barbadian Dollar',
              'BDT': 'Bangladeshi Taka',
              'BGN': 'Bulgarian Lev',
              'BHD': 'Bahraini Dinar',
              'BIF': 'Burundian Franc',
              'BMD': 'Bermudan Dollar',
              'BND': 'Brunei Dollar',
              'BOB': 'Bolivian Boliviano',
              'BRL': 'Brazilian Real',
              'BSD': 'Bahamian Dollar',
              'BTC': 'Bitcoin',
              'BTN': 'Bhutanese Ngultrum',
              'BWP': 'Botswanan Pula',
              'BYN': 'New Belarusian Ruble',
              'BYR': 'Belarusian Ruble',
              'BZD': 'Belize Dollar',
              'CAD': 'Canadian Dollar',
              'CDF': 'Congolese Franc',
              'CHF': 'Swiss Franc',
              'CLF': 'Chilean Unit of Account (UF)',
              'CLP': 'Chilean Peso',
              'CNY': 'Chinese Yuan',
              'COP': 'Colombian Peso',
              'CRC': 'Costa Rican Colón',
              'CUC': 'Cuban Convertible Peso',
              'CUP': 'Cuban Peso',
              'CVE': 'Cape Verdean Escudo',
              'CZK': 'Czech Republic Koruna',
              'DJF': 'Djiboutian Franc',
              'DKK': 'Danish Krone',
              'DOP': 'Dominican Peso',
              'DZD': 'Algerian Dinar',
              'EGP': 'Egyptian Pound',
              'ERN': 'Eritrean Nakfa',
              'ETB': 'Ethiopian Birr',
              'EUR': 'Euro',
              'FJD': 'Fijian Dollar',
              'FKP': 'Falkland Islands Pound',
              'GBP': 'British Pound Sterling',
              'GEL': 'Georgian Lari',
              'GGP': 'Guernsey Pound',
              'GHS': 'Ghanaian Cedi',
              'GIP': 'Gibraltar Pound',
              'GMD': 'Gambian Dalasi',
              'GNF': 'Guinean Franc',
              'GTQ': 'Guatemalan Quetzal',
              'GYD': 'Guyanaese Dollar',
              'HKD': 'Hong Kong Dollar',
              'HNL': 'Honduran Lempira',
              'HRK': 'Croatian Kuna',
              'HTG': 'Haitian Gourde',
              'HUF': 'Hungarian Forint',
              'IDR': 'Indonesian Rupiah',
              'ILS': 'Israeli New Sheqel',
              'IMP': 'Manx pound',
              'INR': 'Indian Rupee',
              'IQD': 'Iraqi Dinar',
              'IRR': 'Iranian Rial',
              'ISK': 'Icelandic Króna',
              'JEP': 'Jersey Pound',
              'JMD': 'Jamaican Dollar',
              'JOD': 'Jordanian Dinar',
              'JPY': 'Japanese Yen',
              'KES': 'Kenyan Shilling',
              'KGS': 'Kyrgystani Som',
              'KHR': 'Cambodian Riel',
              'KMF': 'Comorian Franc',
              'KPW': 'North Korean Won',
              'KRW': 'South Korean Won',
              'KWD': 'Kuwaiti Dinar',
              'KYD': 'Cayman Islands Dollar',
              'KZT': 'Kazakhstani Tenge',
              'LAK': 'Laotian Kip',
              'LBP': 'Lebanese Pound',
              'LKR': 'Sri Lankan Rupee',
              'LRD': 'Liberian Dollar',
              'LSL': 'Lesotho Loti',
              'LTL': 'Lithuanian Litas',
              'LVL': 'Latvian Lats',
              'LYD': 'Libyan Dinar',
              'MAD': 'Moroccan Dirham',
              'MDL': 'Moldovan Leu',
              'MGA': 'Malagasy Ariary',
              'MKD': 'Macedonian Denar',
              'MMK': 'Myanma Kyat',
              'MNT': 'Mongolian Tugrik',
              'MOP': 'Macanese Pataca',
              'MRO': 'Mauritanian Ouguiya',
              'MUR': 'Mauritian Rupee',
              'MVR': 'Maldivian Rufiyaa',
              'MWK': 'Malawian Kwacha',
              'MXN': 'Mexican Peso',
              'MYR': 'Malaysian Ringgit',
              'MZN': 'Mozambican Metical',
              'NAD': 'Namibian Dollar',
              'NGN': 'Nigerian Naira',
              'NIO': 'Nicaraguan Córdoba',
              'NOK': 'Norwegian Krone',
              'NPR': 'Nepalese Rupee',
              'NZD': 'New Zealand Dollar',
              'OMR': 'Omani Rial',
              'PAB': 'Panamanian Balboa',
              'PEN': 'Peruvian Nuevo Sol',
              'PGK': 'Papua New Guinean Kina',
              'PHP': 'Philippine Peso',
              'PKR': 'Pakistani Rupee',
              'PLN': 'Polish Zloty',
              'PYG': 'Paraguayan Guarani',
              'QAR': 'Qatari Rial',
              'RON': 'Romanian Leu',
              'RSD': 'Serbian Dinar',
              'RUB': 'Russian Ruble',
              'RWF': 'Rwandan Franc',
              'SAR': 'Saudi Riyal',
              'SBD': 'Solomon Islands Dollar',
              'SCR': 'Seychellois Rupee',
              'SDG': 'Sudanese Pound',
              'SEK': 'Swedish Krona',
              'SGD': 'Singapore Dollar',
              'SHP': 'Saint Helena Pound',
              'SLL': 'Sierra Leonean Leone',
              'SOS': 'Somali Shilling',
              'SRD': 'Surinamese Dollar',
              'STD': 'São Tomé and Príncipe Dobra',
              'SVC': 'Salvadoran Colón',
              'SYP': 'Syrian Pound',
              'SZL': 'Swazi Lilangeni',
              'THB': 'Thai Baht',
              'TJS': 'Tajikistani Somoni',
              'TMT': 'Turkmenistani Manat',
              'TND': 'Tunisian Dinar',
              'TOP': 'Tongan Paʻanga',
              'TRY': 'Turkish Lira',
              'TTD': 'Trinidad and Tobago Dollar',
              'TWD': 'New Taiwan Dollar',
              'TZS': 'Tanzanian Shilling',
              'UAH': 'Ukrainian Hryvnia',
              'UGX': 'Ugandan Shilling',
              'USD': 'United States Dollar',
              'UYU': 'Uruguayan Peso',
              'UZS': 'Uzbekistan Som',
              'VEF': 'Venezuelan Bolívar Fuerte',
              'VND': 'Vietnamese Dong',
              'VUV': 'Vanuatu Vatu',
              'WST': 'Samoan Tala',
              'XAF': 'CFA Franc BEAC',
              'XAG': 'Silver (troy ounce)',
              'XAU': 'Gold (troy ounce)',
              'XCD': 'East Caribbean Dollar',
              'XDR': 'Special Drawing Rights',
              'XOF': 'CFA Franc BCEAO',
              'XPF': 'CFP Franc',
              'YER': 'Yemeni Rial',
              'ZAR': 'South African Rand',
              'ZMK': 'Zambian Kwacha (pre-2013)',
              'ZMW': 'Zambian Kwacha',
              'ZWL': 'Zimbabwean Dollar'}
